server:
  url: "http://localhost"
  port: 5001
  servlet:
    context-path: /api/keycloak

frontend:
  url: "http://localhost:3000"

users-posts:
  url: "http://localhost:5002"
  context-path: ${users-posts.url}/api/users_posts
  users-controller: ${users-posts.context-path}/users
  add-user: ${users-posts.users-controller}/add

keycloak:
  port : 8282
  url: "${server.url}:${keycloak.port}"
  realm: "repaintinggame"
  jwt:
    auth:
      converter:
        principle-attribute: preferred_username
        resource-id: repaint-game

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${keycloak.url}/realms/${keycloak.realm}
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /api-docs
